#!/usr/bin/env bash

pause() {
  echo
  read -n 1 -s -r -p "Press any key to continue..."
  echo
}

if [[ -n "$EC_PARROT_OUTSIDE" ]]; then
  section="outside"
elif [[ -n "$EC_PARROT_FREED" ]]; then
  section="freed"
else
  section="caged"
fi

case "$section" in

  freed)
    echo
    echo "The parrot flies in circles around the room, pecking at the wizard."
    echo
    echo '"CWAAAAK! You freed me! CWAAAAK! Pokkie outside!"'
    echo
    pause
    echo
    echo "Pokkie sits down on your shoulder."
    echo

    export EC_PARROT_OUTSIDE=true

    script_path="$(realpath "${BASH_SOURCE[0]}")"
    script_dir="$(dirname "$script_path")"
    dest_dir="$(realpath "$script_dir/../../../")"

    mkdir -p "$dest_dir"
    mv -f "$script_path" "$dest_dir/"

  ;;

  outside)
    echo
    echo "Pokkie gives you a long stare, before she begins to speak."
    echo
    pause
    echo
    echo '"This game was developed by Extra Nice in Leeuwarden in association with VU."'
    echo
    curl -s parrot.live
  ;;

  caged)
    echo
    echo "The parrot sits in the cage and shakes, eyeing the wizard."
    echo
    pause
    echo
    echo "As you come closer, she looks at you."
    echo
    echo '"CWAAAK! `cage open`!"'
    echo
    pause
    echo
    echo '"CWAAAK! `cage open`!"'
    echo

    if [[ "$EC_WIZARD_ATTIC" == "true" ]]; then
      echo "The wizard looks at you with a red face. \"Don't you dare type \`. cage open\`!\""
      echo 
    fi
    ;;
esac

