#!/bin/bash

pause() {
  echo
  read -n 1 -s -r -p "Press any key to continue..."
  echo
}

echo
echo "You approach the gnome. He's holding a wand in his hand."
echo "He gives you a blank stare."
echo
pause
echo
echo "\"Huh? Where did you come from. Oh well, since you're already inside I don't need to worry I guess.\""
echo "You tell him that you want to save Pokkie."
echo
pause
echo
echo "\"I see. The parrot. Might as well help you then."
echo "But don't tell the wizard, or he'll turn me into a bunch of paperclips.\""
echo
pause
echo
echo "\"So as you can see (with \`ls\`), there are a bunch of rooms around here."
echo "To go into a room, just type \`cd whatever\` and you go into it.\""
echo
pause
echo
echo "\"I know, a bit strange, but that's how things work around here."
echo "Ah yeah, if you don't know already, you can type \`cd ..\` to come out of a room again.\""
echo
pause
echo
echo "\"Also, you should really read the house rules.\""
echo "He points at a paper on the wall (rules.txt)."
echo "\"Just type \`xdg-open rules.txt\` to read them, will you?\""
echo
pause
echo
echo "\"So, uh... if there isn't anything else, I'll get back to guarding the front door now."
echo "My job is to turn intruders into stone, so you know, I'm really important around here.\""
echo
